# ... is replacement for pass
class DataIngestionArtifcat:...
class DataValidationArtifcat:...
class DataTransformationArtifcat:...
class ModelTrainerArtifcat:...
class ModelEvaluationArtifcat:...
class ModelPusherArtifcat:...
